#!/usr/bin/perl

use strict;
use Spread::Queue::Manager;
use Log::Channel;
use Getopt::Long;

my $verbose;
GetOptions("verbose|v=i" => \$verbose) or die;

enable Log::Channel "Spread::Session" if $verbose > 1;
enable Log::Channel "Spread::Queue::Manager" if $verbose > 0;
enable Log::Channel "Spread::Session::message" if $verbose > 1;
enable Log::Channel "Spread::Queue::FIFO" if $verbose > 1;

my $queue_name = shift @ARGV || die "usage: sqm [-v {0,1}] queue-name";

my $session = new Spread::Queue::Manager(QUEUE => $queue_name);

$session->run;
